### ISSUE TITLE
ERROR: Cannot install openai because these package versions have conflicting dependencies. 

### ISSUE THREAD

**Issue by naigri** [VideotronicMaker/LM_Studio_Local_Server#1]
Thank you for your project.

During the step-by-step installation, an error occurred while installing the requirements: ERROR: Cannot install openai because these package versions have conflicting dependencies. The error message indicates a requirement for depending on certifi>=2017.4.17, but I am unsure how to proceed.

I then modified the requirements to specify openai>=0.28.0. Although this installation succeeded, the update to the API usage in openai versions greater than 1.0 rendered the openai.ChatCompletion.create method unavailable.

Subsequently, I copied the Assistant sample code provided by LM Studio, which runs successfully.

**Comment by VideotronicMaker** [comment]
I will look into this soon.  I am glad to hear that you got it working using the LM Studio code.  It works for some and not for others.  I hope to find out why.  Thx for your post.
